There are two types of categorial data. 1:nominal categorical data, 2:ordinal categorial data.
In a dataset, we can have both types of categorial data and we have to deal with both the types separapately by fetching out the features from the dataframe and applying OrdinalEncoder for ordinal categorical data and OneHotEncoder for nominal categorial data. After we convert all the features into numerical data, we concatenate all the arrays and make a single array or dataframe. THIS IS A MANNUAL AND TEDIOUS PROCESS. In order to make things interesting and efficient, we have something know as ColumnTransformer which does this with few lines of code. In this notebook, I have done through a mannual approach. Kindly visit the repo to get a codes using ColumnTransformer

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
data_second = pd.read_csv('D:/datasets/purchased.csv')

In [3]:
data_second.head()

age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [4]:
x_train, x_test, y_train, y_test = train_test_split(data_second.iloc[:,0:4], data_second.iloc[:,-1], test_size=0.1)
x_train.shape

(45, 4)

In [5]:
data_second['education'].value_counts()

PG        18
UG        16
School    16
Name: education, dtype: int64

In [6]:
data_second['review'].value_counts()

Good       18
Poor       18
Average    14
Name: review, dtype: int64

In [7]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [8]:
oe.fit(x_train[['review','education']])

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [9]:
train_transformed = oe.transform(x_train[['review','education']])
test_transformed = oe.transform(x_test[['review','education']])

In [10]:
train_transformed[0:5]

array([[2., 0.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [1., 1.]])

In [11]:
x_train[['review','education']].head()

review education
40     Good    School
32  Average        UG
35     Poor    School
26     Poor        PG
44  Average        UG

If we look cell 10 and cell 11, the numeric values have been assigned to ['Poor', 'Average', 'Good'],
['School', 'UG', 'PG'] accordingly. 

In [12]:
ohe_second = OneHotEncoder(drop='first', sparse=False, dtype=np.int32)
ohe_second.fit(x_train[['gender']])
gender_train = ohe_second.transform(x_train[['gender']])
gender_test = ohe_second.transform(x_test[['gender']])

In [13]:
gender_train[0:5]

array([[1],
       [1],
       [1],
       [0],
       [0]])

In [14]:
x_train[['gender']].head()

gender
40    Male
32    Male
35    Male
26  Female
44  Female

Now, we have to concatenate everything... !!! Let's simply do ColumnTransformer

In [17]:
le = LabelEncoder()
le.fit(y_test)
train_label = le.transform(y_train)
test_label = le.transform(y_test)

As our output column is also in categorial form, we have to convert it into numerical as well. For output feature, we use 
LabelEncoder. 

In [19]:
train_label[0:5]

array([0, 1, 1, 0, 0])

In [20]:
y_train.head()

40     No
32    Yes
35    Yes
26     No
44     No
Name: purchased, dtype: object

we can see 0 == NO and 1 == Yes